language: node_js

node_js:
  - 14

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_registration_tests

before_script:
  - psql -c 'create database  my_registration_tests;' -U postgres
  - psql -U postgres -d my_registration_tests -a -f users.sql 

services:
  - postgresql